# Generated by Django 2.1 on 2018-08-03 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20180802_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='quantidade',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 0, 49, 31, 696368, tzinfo=utc)),
        ),
    ]
