# Generated by Django 2.1 on 2018-08-07 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_auto_20180806_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 7, 1, 18, 16, 80923, tzinfo=utc)),
        ),
    ]
