# Generated by Django 2.1.1 on 2018-09-05 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_auto_20180806_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 17, 3, 8, 399785, tzinfo=utc)),
        ),
    ]
