# Generated by Django 2.1 on 2018-09-05 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_auto_20180905_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 22, 57, 8, 980629, tzinfo=utc)),
        ),
    ]
