# Generated by Django 2.1 on 2018-09-05 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_auto_20180905_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 5, 23, 3, 12, 168790, tzinfo=utc)),
        ),
    ]
