# Generated by Django 2.1.1 on 2018-09-06 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0017_auto_20180905_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 13, 35, 44, 239657, tzinfo=utc)),
        ),
    ]
