# Generated by Django 2.1 on 2018-09-07 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0023_auto_20180906_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 0, 21, 20, 171518, tzinfo=utc)),
        ),
    ]
