# Generated by Django 2.1 on 2018-09-07 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0024_auto_20180906_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 0, 23, 26, 977962, tzinfo=utc)),
        ),
    ]
