# Generated by Django 2.1 on 2018-09-07 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0038_auto_20180907_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 16, 54, 38, 506929, tzinfo=utc)),
        ),
    ]
