# Generated by Django 2.1 on 2018-09-07 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0044_auto_20180907_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 7, 20, 44, 0, 229975, tzinfo=utc)),
        ),
    ]
