# Generated by Django 2.1 on 2018-09-24 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0051_auto_20180907_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 21, 35, 3, 818983, tzinfo=utc)),
        ),
    ]
