# Generated by Django 2.1.2 on 2018-10-15 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0053_auto_20180924_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 17, 23, 29, 516346, tzinfo=utc)),
        ),
    ]
