# Generated by Django 2.1.2 on 2018-10-15 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0054_auto_20181015_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 17, 26, 42, 298673, tzinfo=utc)),
        ),
    ]
