# Generated by Django 2.1.2 on 2018-10-15 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0059_auto_20181015_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 18, 8, 18, 678897, tzinfo=utc)),
        ),
    ]
