# Generated by Django 2.1.2 on 2018-10-18 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0061_auto_20181015_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 13, 28, 11, 955364, tzinfo=utc)),
        ),
    ]
