# Generated by Django 2.1.2 on 2018-10-18 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0063_auto_20181018_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 13, 44, 40, 257699, tzinfo=utc)),
        ),
    ]
