# Generated by Django 2.1.2 on 2018-10-18 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0064_auto_20181018_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 14, 2, 59, 313668, tzinfo=utc)),
        ),
    ]
